import type { AnalysisCategory } from './types';

export const ANALYSIS_CATEGORIES: AnalysisCategory[] = [
  {
    id: 'morphology',
    label: 'Morfologia',
    shortLabel: 'Morf.',
    description: 'Budulec języka — klasy słów, typy rzeczowników i czasowników, zaimki, negacje',
    analyses: [
      {
        id: 'pos-distribution',
        label: 'Części mowy — rozkład',
        description: 'Ile rzeczowników, czasowników, przymiotników? Rozkład procentowy.',
        definition: 'Ta analiza pokazuje, z jakich klas słów zbudowany jest wiersz albo cała twórczość. Jej celem jest uchwycenie podstawowego profilu językowego tekstu: czy dominuje nazewnictwo, działanie, opis czy relacje. W trybie pojedynczego wiersza pokazuje mikroprofil konkretnego tekstu. W trybie całości odsłania dominujący styl językowy autora.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'noun-concrete-abstract',
        label: 'Rzeczowniki — konkret vs abstrakt',
        description: 'Poeta ciała czy metafizyki? Proporcja materialnych do pojęciowych.',
        definition: 'Ta analiza pokazuje, czy rzeczowniki odnoszą się częściej do rzeczy materialnych i zmysłowych, czy do pojęć ogólnych i abstrakcyjnych. Jej celem jest uchwycenie napięcia między konkretnością a metafizycznością języka. W pojedynczym wierszu ujawnia, czy tekst jest bardziej cielesny czy pojęciowy. W całej twórczości pokazuje ogólny profil słownika rzeczownikowego.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'verb-tenses',
        label: 'Czasowniki — tryby i czasy',
        description: 'Bezokoliczniki, tryby, czasy — jak działa sprawczość i czas w wierszu.',
        definition: 'Ta analiza pokazuje, jak w wierszu organizowane są czas i sprawczość. Szczególnie ważne są bezokoliczniki i formy bezosobowe, bo sygnalizują wycofanie podmiotu lub depersonalizację działania. W pojedynczym wierszu ujawnia lokalny sposób budowania ruchu i sprawczości. W całej twórczości pokazuje trwałe preferencje stylistyczne.',
        chartType: 'pie' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'verb-semantics',
        label: 'Czasowniki — semantyka akcji',
        description: 'Ruch, percepcja, stan, destrukcja — jaki typ działania dominuje?',
        definition: 'Ta analiza pokazuje, jakie typy działań dominują w wierszu. Jej celem jest ustalenie, czy tekst opiera się bardziej na ruchu, percepcji, stanie, destrukcji, komunikacji czy czynnościach ciała. Dzięki temu odsłania się model działania, który organizuje świat przedstawiony.',
        chartType: 'radar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'adj-types',
        label: 'Przymiotniki — paleta opisu',
        description: 'Zmysłowe, oceniające, opisowe — jak poeta charakteryzuje świat?',
        definition: 'Ta analiza pokazuje, jaką funkcję pełnią przymiotniki w tekście. Jej celem jest ustalenie, czy opis jest bardziej zmysłowy, oceniający czy neutralno-opisowy. Dzięki temu widać, czy poeta buduje świat przez doznania, wartościowanie czy klasyczny opis cech.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'adverbs',
        label: 'Przysłówki — sposób, czas, modalność',
        description: 'Jak dzieją się rzeczy — kiedy, jak, z jaką pewnością.',
        definition: 'Ta analiza pokazuje, jak dzieją się rzeczy w wierszu: kiedy, w jaki sposób i z jakim stopniem pewności. Jej celem jest uchwycenie warstwy doprecyzowań, które organizują rytm, ton i modalność wypowiedzi.',
        chartType: 'list' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'pronouns',
        label: 'Zaimki — kto mówi do kogo',
        description: 'Ja, ty, on — rozkład ról osoby mówiącej i adresata.',
        definition: 'Ta analiza pokazuje układ osób w tekście: kto mówi, do kogo mówi i kto jest obecny w świecie wiersza. Jej celem jest uchwycenie relacyjności wypowiedzi i stopnia obecności podmiotu. Dzięki niej widać, czy tekst jest osobisty, dialogowy czy bezosobowy.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'negations',
        label: 'Negacje — język zaprzeczania',
        description: 'Język odmowy i braku — nie, nic, nikt, nigdy.',
        definition: 'Ta analiza pokazuje, jak silnie tekst opiera się na odmowie, braku i zaprzeczeniu. Jej celem jest uchwycenie negacyjnego napięcia języka i skali wycofania świata przedstawionego. Dzięki niej widać, czy negacja jest tylko elementem stylu, czy jedną z osi organizujących sens wiersza.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'syntax',
    label: 'Składnia',
    shortLabel: 'Skł.',
    description: 'Architektura zdań — długość, typy, fragmentaryczność, przerzutnie, szyk',
    analyses: [
      {
        id: 'sentence-length',
        label: 'Długość zdań',
        description: 'Telegraficzny czy narracyjny? Średnia, mediana, rozkład.',
        definition: 'Ta analiza pokazuje, jak długie są zdania w wierszu i jak rozkłada się ich długość. Jej celem jest uchwycenie, czy styl jest bardziej telegraficzny i urywany, czy narracyjny i rozwinięty. Dzięki niej widać rytm składni oraz tempo rozwijania myśli.',
        chartType: 'histogram' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'line-length',
        label: 'Długość wersów',
        description: 'Ile słów i sylab na wers — regularność czy chaos?',
        definition: 'Ta analiza pokazuje, jak długie są wersy i czy ich budowa jest regularna. Jej celem jest uchwycenie organizacji wersu na poziomie słów i sylab. Dzięki niej widać, czy poeta utrzymuje rytmiczną dyscyplinę, czy świadomie rozsadza regularność.',
        chartType: 'histogram' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'sentence-types',
        label: 'Typy zdań',
        description: 'Stwierdza, pyta, rozkazuje czy wybucha? Proporcje.',
        definition: 'Ta analiza pokazuje, jaki typ wypowiedzi dominuje w tekście. Jej celem jest ustalenie, czy wiersz głównie stwierdza, pyta, rozkazuje czy wybucha emocją. Dzięki temu można zobaczyć podstawowy tryb komunikacyjny utworu.',
        chartType: 'pie' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'ellipsis',
        label: 'Elipsy i urwania',
        description: 'Ile zdań jest niepełnych, urwanych, pękniętych?',
        definition: 'Ta analiza pokazuje, na ile tekst jest pełny składniowo, a na ile oparty na brakach, niedopowiedzeniach i pęknięciach. Jej celem jest uchwycenie stopnia fragmentaryczności wypowiedzi.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'enjambement',
        label: 'Przerzutnie',
        description: 'Ile razy zdanie rozlewa się na następny wers?',
        definition: 'Ta analiza pokazuje, jak często sens i składnia przechodzą z jednego wersu do następnego. Jej celem jest uchwycenie napięcia między granicą wersową a ciągłością zdania. Dzięki niej widać, czy wers jest jednostką zamkniętą, czy raczej otwartą i przepływową.',
        chartType: 'info' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'word-order',
        label: 'Szyk zdania i inwersje',
        description: 'Naturalny szyk czy poetyckie odwrócenia?',
        definition: 'Ta analiza pokazuje, jak często poeta odchodzi od naturalnego porządku zdania. Jej celem jest uchwycenie napięcia między składnią normatywną a poetyckim przestawieniem. Dzięki niej widać, czy tekst buduje efekt przez inwersję, przesunięcie akcentu i zaburzenie kolejności.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'phonetics',
    label: 'Fonetyka',
    shortLabel: 'Fon.',
    description: 'Dźwięk wiersza — samogłoski, spółgłoski, zbitki, rymy, profil głoskowy',
    analyses: [
      {
        id: 'vowel-consonant',
        label: 'Samogłoski vs spółgłoski',
        description: 'Miękko i wokalicznie czy twardo i chropawo?',
        definition: 'Ta analiza pokazuje ogólny profil brzmieniowy tekstu. Jej celem jest uchwycenie, czy wiersz brzmi bardziej miękko i wokalicznie, czy twardo i spółgłoskowo. Dzięki niej można opisać podstawowy charakter foniczny utworu.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'consonant-clusters',
        label: 'Grupy spółgłoskowe',
        description: 'Trudne, gęste układy głosek — ostrość dźwięku.',
        definition: 'Ta analiza pokazuje natężenie trudnych, gęstych układów spółgłoskowych. Jej celem jest uchwycenie ostrości i chropowatości dźwiękowej tekstu. Dzięki niej widać, czy poeta wzmacnia efekt napięcia przez fonetyczne zagęszczenie.',
        chartType: 'list' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'rhymes',
        label: 'Rymy, asonanse i aliteracje',
        description: 'Powtarzalność dźwiękowa — rymy i echo głosek.',
        definition: 'Ta analiza pokazuje powtarzalność dźwięków w obrębie końcówek wersów i wnętrza tekstu. Jej celem jest uchwycenie formalnej i brzmieniowej organizacji wiersza.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'sound-groups',
        label: 'Instrumentacja głoskowa',
        description: 'Szumiące, syczące, nosowe, płynne — charakter foniczny.',
        definition: 'Ta analiza pokazuje dominujący charakter foniczny utworu. Jej celem jest uchwycenie, czy wiersz szumi, syczy, mruczy czy płynie. Dzięki niej można opisać głoskowy podpis tekstu.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'semantics',
    label: 'Semantyka',
    shortLabel: 'Sem.',
    description: 'Pola znaczeń — tematy, opozycje, metafory, epitety',
    analyses: [
      {
        id: 'semantic-fields',
        label: 'Pola semantyczne',
        description: 'Ciało, śmierć, erotyka, sacrum — które tematy dominują?',
        definition: 'Ta analiza pokazuje, jakie obszary znaczeń dominują w wierszu lub całej twórczości. Jej celem jest uchwycenie mapy głównych tematów i rejestrów sensu. Dzięki niej widać, czy tekst koncentruje się na ciele, śmierci, erotyce, sacrum, naturze czy innych polach.',
        chartType: 'radar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'metaphors',
        label: 'Metafory — źródło i cel',
        description: 'Co jest metaforą czego — domeny obrazowe poety.',
        definition: 'Ta analiza pokazuje, z jakich obszarów doświadczenia poeta bierze obrazy metaforyczne i do czego je odnosi. Jej celem jest uchwycenie sposobu przekładania jednych domen sensu na inne. Dzięki niej widać, czy śmierć bywa opisywana językiem ciała, religii, przedmiotów, przestrzeni czy ruchu.',
        chartType: 'list' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'word-cloud',
        label: 'Chmura słów',
        description: 'Najczęstsze słowa — wizualna mapa leksyki.',
        definition: 'Słowa uporządkowane według częstotliwości. Im większe słowo, tym częściej występuje. Chmura ujawnia obsesje leksykalne poety.',
        chartType: 'wordcloud' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'bigrams',
        label: 'Najczęstsze bigramy',
        description: 'Pary słów występujące razem — co poeta mówi dwoma słowami?',
        definition: 'Bigram to para dwóch sąsiadujących słów w tekście — np. „nie ma", „moje ciało", „ja jestem". W lingwistyce korpusowej bigramy (i ich rozszerzenia: trigramy, n-gramy) służą do analizy nawykowych połączeń wyrazowych, które ujawniają nieświadome wzorce stylu autora. Najczęstsze bigramy to językowy „podpis" poety — frazy, do których wraca obsesyjnie. U Wojaczka dominują połączenia z negacją („nie ma", „nie jest", „już nie") i cielesnością („moje ciało"), co potwierdza dwa fundamenty jego poetyki: zaprzeczanie i fizyczność. W porównaniu z normą polszczyzny literackiej Wojaczek ma nietypowo wysoki udział bigramów z zaimkiem „ja" — sygnał skrajnej konfesyjności. Wizualizacja sieciowa pokazuje, które słowa tworzą klastry połączeń — im więcej krawędzi wychodzi z węzła, tym bardziej centralne jest to słowo w leksyce poety.',
        chartType: 'list' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'subject',
    label: 'Podmiot liryczny',
    shortLabel: 'Podm.',
    description: 'Kto mówi — obecność ja, adresat, emocje, autodestrukcja',
    analyses: [
      {
        id: 'subject-presence',
        label: 'Obecność podmiotu',
        description: 'Jawne ja, ukryte czy bezosobowe?',
        definition: 'Ta analiza pokazuje, czy mówiący ujawnia się wyraźnie, pozostaje ukryty, czy znika w bezosobowości. Jej celem jest uchwycenie stopnia obecności ja w tekście. Dzięki niej widać, czy wiersz ma charakter wyznaniowy, zdystansowany czy anonimowy.',
        chartType: 'pie' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'addressee',
        label: 'Adresat — do kogo mówi',
        description: 'Do ty, do Boga, do siebie, do nikogo?',
        definition: 'Ta analiza pokazuje, do kogo skierowany jest wiersz. Jej celem jest uchwycenie układu komunikacyjnego i typu relacji tworzonej przez tekst. Dzięki niej widać, czy wiersz przemawia do konkretnej osoby, Boga, samego siebie, czy nie wskazuje żadnego adresata.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'mask-sincerity',
        label: 'Maska czy szczerość',
        description: 'Konfesja czy kreacja — na ile podmiot jest autorem?',
        definition: 'Ta analiza pokazuje, na ile podmiot wydaje się konfesyjny, a na ile wykreowany jako rola lub maska. Jej celem jest uchwycenie stopnia autobiograficzności i dystansu do własnej wypowiedzi.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'emotion',
        label: 'Profil emocjonalny',
        description: 'Gniew, rezygnacja, ironia, czułość — z jaką siłą?',
        definition: 'Ta analiza pokazuje, jakie emocje dominują w wierszu i z jaką siłą są obecne. Jej celem jest uchwycenie afektywnego profilu tekstu. Dzięki niej widać, czy utwór opiera się na gniewie, smutku, strachu, ironii, rezygnacji czy czułości.',
        chartType: 'radar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'autodestruction',
        label: 'Autodestrukcja',
        description: 'Język samozniszczenia, rozpadu, rezygnacji z istnienia.',
        definition: 'Ta analiza pokazuje, na ile tekst zawiera język samounicestwienia, rozpadu, rezygnacji z istnienia albo przemocy skierowanej do siebie. Wrażliwy temat — wizualizacja z disclaimerem i informacją o pomocy kryzysowej.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'intertextuality',
    label: 'Intertekstualność',
    shortLabel: 'Inter.',
    description: 'Kto kogo cytuje — aluzje, autopowtórzenia, wpływy',
    analyses: [
      {
        id: 'allusions',
        label: 'Aluzje literackie',
        description: 'Biblia, mitologia, inni poeci — do czego nawiązuje?',
        definition: 'Ta analiza pokazuje, do jakich tekstów, tradycji i autorów wiersz nawiązuje. Jej celem jest uchwycenie osadzenia utworu w sieci odniesień kulturowych. Dzięki niej widać, czy dominują odwołania biblijne, mitologiczne czy poetyckie.',
        chartType: 'list' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'anaphors',
        label: 'Anafory i powtórzenia',
        description: 'Które frazy otwierają wersy wielokrotnie?',
        definition: 'Ta analiza pokazuje, jakie frazy, obrazy i połączenia słów poeta powtarza. Anafora to powtórzenie słowa lub frazy na początku kolejnych wersów — to podpis stylistyczny Wojaczka.',
        chartType: 'list' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'influences',
        label: 'Wpływy i podobieństwa stylu',
        description: 'Rimbaud, Baudelaire, Bursa, Różewicz — kto brzmi podobnie?',
        definition: 'Ta analiza pokazuje, do których poetów dany wiersz lub cała twórczość są najbardziej podobne stylistycznie. Jej celem jest uchwycenie statystycznego pokrewieństwa stylów.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'climate',
    label: 'Klimat i nastrój',
    shortLabel: 'Klim.',
    description: 'Atmosfera — zmysły, przestrzeń, czas, ruch, temperatura emocjonalna',
    analyses: [
      {
        id: 'senses',
        label: 'Paleta sensoryczna',
        description: 'Wzrok, słuch, dotyk, smak, zapach — który zmysł dominuje?',
        definition: 'Ta analiza pokazuje, które zmysły są najmocniej aktywowane przez język wiersza. Jej celem jest uchwycenie sensorycznego profilu utworu. Dzięki niej widać, czy tekst przemawia głównie obrazem, dźwiękiem, dotykiem, smakiem czy zapachem.',
        chartType: 'radar' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'temperature',
        label: 'Temperatura emocjonalna',
        description: 'Gorące (gniew, pożądanie) <-> zimne (rezygnacja, pustka).',
        definition: 'Ta analiza pokazuje, czy klimat emocjonalny wiersza jest gorący i gwałtowny, czy zimny, pusty i wygaszony. Jej celem jest uchwycenie ogólnej temperatury afektywnej tekstu.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'space',
        label: 'Przestrzeń wiersza',
        description: 'Zamknięta (pokój, klatka) czy otwarta (ulica, niebo)?',
        definition: 'Ta analiza pokazuje, czy świat tekstu jest bardziej zamknięty i klaustrofobiczny, czy otwarty i ekspansywny. Jej celem jest uchwycenie przestrzennego nastroju wiersza.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'time-of-day',
        label: 'Pora dnia i cykliczność',
        description: 'Noc, rano, wieczór — w jakim czasie żyje wiersz?',
        definition: 'Ta analiza pokazuje, w jakim czasie symbolicznym i dobowym osadzony jest wiersz. Jej celem jest uchwycenie dominujących pór dnia i sezonów.',
        chartType: 'info' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'motion',
        label: 'Ruch vs bezruch',
        description: 'Dynamiczny czy zastygły — co się dzieje w wierszu?',
        definition: 'Ta analiza pokazuje, czy wiersz jest dynamiczny, czy raczej zatrzymany i nieruchomy. Jej celem jest uchwycenie poziomu mobilności świata przedstawionego.',
        chartType: 'scale' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'imagery-density',
        label: 'Gęstość obrazowania',
        description: 'Ile metafor, porównań, personifikacji na 100 słów?',
        definition: 'Ta analiza pokazuje, jak bardzo tekst jest figuratywny i obrazowy. Jej celem jest uchwycenie nasycenia metaforami, porównaniami, personifikacjami i hiperbolami.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
  {
    id: 'metrics',
    label: 'Metryka i rytm',
    shortLabel: 'Metr.',
    description: 'Organizacja rytmiczna — metrum, strofika, tempo czytania',
    analyses: [
      {
        id: 'regularity',
        label: 'Regularność metryczna',
        description: 'Jamb, trochej, wiersz wolny — jaki rytm dominuje?',
        definition: 'Ta analiza pokazuje, czy wiersz opiera się na regularnym rytmie, czy na wolnym i niestabilnym przebiegu. Wojaczek pisze prawie wyłącznie wierszem wolnym.',
        chartType: 'info' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'strophic',
        label: 'Strofika',
        description: 'Ile zwrotek, ile wersów — regularna czy wolna forma?',
        definition: 'Ta analiza pokazuje, jak zbudowany jest wiersz jako całość formalna. Jej celem jest uchwycenie organizacji stroficznej i rozkładu wersów.',
        chartType: 'info' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'reading-tempo',
        label: 'Tempo czytania',
        description: 'Szybki czy wolny wiersz — ile sylab, ile pauz?',
        definition: 'Ta analiza pokazuje, jak szybko lub wolno wiersz rozwija się w głośnej lekturze. Szacunkowy czas obliczany na podstawie liczby sylab (~3 sylaby/sekundę) i pauz interpunkcyjnych.',
        chartType: 'info' as const,
        modes: ['poem', 'corpus'] as const,
      },
      {
        id: 'fractal',
        label: 'Analiza fraktalna',
        description: 'Czy struktura wierszy Wojaczka ma charakter fraktalny? Wykładnik Hursta i DFA.',
        definition: 'Analiza fraktalna bada, czy wzorce długości zdań i wersów powtarzają się na różnych skalach — jak fraktale w matematyce. Wykładnik Hursta (H) mierzy persystencję rytmu: H powyżej 0.5 oznacza że po długim zdaniu częściej następuje kolejne długie — styl jest płynny i narracyjny. H poniżej 0.5 oznacza że po długim zdaniu następuje krótkie — styl telegraficzny, poszarpany, kontrastowy. H równe 0.5 to brak wzorca, losowość. DFA (Detrended Fluctuation Analysis) potwierdza wynik eliminując lokalne trendy. Dzięki tej analizie widać, czy poeta buduje tekst organicznie (z powtarzalnymi wzorcami) czy chaotycznie.',
        chartType: 'bar' as const,
        modes: ['poem', 'corpus'] as const,
      },
    ],
  },
];
