# Generated by Django 5.2.12 on 2026-03-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL obrazu')),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Plik obrazu')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Obraz galerii',
                'verbose_name_plural': 'Obrazy galerii',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=200, verbose_name='Adresat')),
                ('date', models.CharField(max_length=50, verbose_name='Data')),
                ('excerpt', models.TextField(verbose_name='Fragment')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Listy',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('year', models.CharField(blank=True, default='', max_length=10, verbose_name='Rok')),
            ],
            options={
                'verbose_name': 'Wiersz',
                'verbose_name_plural': 'Wiersze',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoria')),
                ('lat', models.FloatField(verbose_name='Szerokość geo.')),
                ('lng', models.FloatField(verbose_name='Długość geo.')),
                ('description', models.TextField(verbose_name='Opis')),
                ('audio_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL audio')),
                ('image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL obrazu')),
                ('duration', models.CharField(blank=True, default='', max_length=20, verbose_name='Czas trwania')),
                ('resource_count', models.IntegerField(default=0, verbose_name='Liczba zasobów')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Miejsce',
                'verbose_name_plural': 'Miejsca',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_center_lat', models.FloatField(default=50.169, verbose_name='Centrum mapy — szer. geo.')),
                ('map_center_lng', models.FloatField(default=18.904, verbose_name='Centrum mapy — dł. geo.')),
                ('map_zoom', models.IntegerField(default=15, verbose_name='Zoom mapy')),
                ('map_detail_zoom', models.IntegerField(default=16, verbose_name='Zoom detalu')),
            ],
            options={
                'verbose_name': 'Ustawienia',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Rok')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Oś czasu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Tekst'), ('photo', 'Zdjęcie'), ('gallery', 'Galeria'), ('audio', 'Audio'), ('video', 'Wideo'), ('map', 'Mapa'), ('beforeAfter', 'Przed/Po'), ('timeline', 'Oś czasu'), ('poem', 'Wiersz')], max_length=20, verbose_name='Typ bloku')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('content', models.JSONField(default=dict, help_text='Dane bloku w formacie JSON. Struktura zależy od typu bloku.', verbose_name='Zawartość')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_blocks', to='content.point', verbose_name='Miejsce')),
            ],
            options={
                'verbose_name': 'Blok mediów',
                'verbose_name_plural': 'Bloki mediów',
                'ordering': ['order'],
            },
        ),
    ]
