# Generated by Django 5.2.12 on 2026-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('file', models.FileField(upload_to='audio/', verbose_name='Plik audio')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Opis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Plik audio',
                'verbose_name_plural': 'Pliki audio',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
