import { GoogleGenAI } from "@google/genai";
import type { AiService } from './aiService';

const REFLECTION_MODEL = "gemini-3-flash-preview";
const IMAGE_MODEL = "gemini-3.1-flash-image-preview";

function getGenAI() {
  const apiKey = process.env.GEMINI_API_KEY || "";
  return new GoogleGenAI({ apiKey });
}

function extractImageFromResponse(response: any): string | null {
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  return null;
}

export const geminiProvider: AiService = {
  async generateReflection(locationName: string): Promise<string | null> {
    const ai = getGenAI();
    const response = await ai.models.generateContent({
      model: REFLECTION_MODEL,
      contents: `Napisz krótką, metafizyczną refleksję (max 3 zdania) o obecności Rafała Wojaczka w miejscu: ${locationName}. Zachowaj mroczny, poetycki ton.`,
      config: {
        systemInstruction: "Jesteś duchem Rafała Wojaczka, polskiego poety wyklętego. Mówisz językiem gęstym, pełnym egzystencjalnego lęku i piękna."
      }
    });
    return response.text ?? null;
  },

  async generateImage(prompt: string): Promise<string | null> {
    const ai = getGenAI();
    const response = await ai.models.generateContent({
      model: IMAGE_MODEL,
      contents: {
        parts: [{ text: `Stwórz artystyczną, minimalistyczną grafikę w skali szarości inspirowaną poezją Rafała Wojaczka. Temat: ${prompt}. Styl: wysoki kontrast, ziarnistość, estetyka czarno-białej fotografii analogowej.` }]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K"
        }
      }
    });
    return extractImageFromResponse(response);
  },

  async generateMockups(): Promise<string[]> {
    const ai = getGenAI();
    const prompts = [
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: INTRO VIEW. High-impact typographic screen. Large bold serif text 'Mapa Obecności'. Minimalist layout, lots of white space (ma). A single artistic grayscale photo. Monochrome, paper texture.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: Interactive grayscale map of Mikołów city with square red markers. Aesthetic: minimalist, paper texture, sharp edges, premium typography (Cormorant Garamond).",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: Long scrolling detail view of a historical location. Includes a grayscale photo, a minimalist audio player with square buttons, and justified serif text with a large dropcap. Aesthetic: artistic minimalism, 90-degree angles, paper texture.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: List of locations. Square grayscale thumbnails, sharp borders, red accent labels. Aesthetic: high-end art publication style, monochrome with red accents.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: BIOGRAPHY VIEW. Large grayscale portrait of a poet. Elegant timeline with thin lines. Bold serif headings. Minimalist, monochrome, sharp edges.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: REFLECTIONS GALLERY. A grid of artistic, abstract grayscale images generated by AI. Minimalist labels with wide tracking. Monochrome, paper texture, high-end design.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: TIMELINE VIEW. Vertical line with square nodes. Years in bold red. Brief descriptions in minimalist sans-serif. Monochrome with red accents, paper texture.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: LETTERS VIEW. Excerpts of handwritten-style text in a minimalist grid. Large 'DO:' labels. Grayscale, elegant, high-end art publication aesthetic.",
      "High-fidelity mobile PWA mockup for 'Wojaczek' app. Screen: POEMS VIEW. Elegant justified serif text. Large titles. Grayscale, minimalist, high-end design."
    ];

    const results = await Promise.all(
      prompts.map(async (prompt) => {
        const response = await ai.models.generateContent({
          model: IMAGE_MODEL,
          contents: { parts: [{ text: prompt }] },
          config: {
            imageConfig: {
              aspectRatio: "9:16",
              imageSize: "1K"
            }
          }
        });
        return extractImageFromResponse(response);
      })
    );

    return results.filter((r): r is string => r !== null);
  }
};
